version: "3.4"

x-development-build: &development-build
  build:
    context: .
    dockerfile: Dockerfile
    args:
      requirement_file: development.txt

x-testing-build: &testing-build
  build:
    context: .
    dockerfile: Dockerfile
    args:
      requirement_file: testing.txt
  volumes:
    - ./reports:/usr/src/app/reports

x-networks: &networks
  networks:
    - ns

x-mounted: &mounted
  volumes:
    - .:/usr/src/app

services:
  {%- if cookiecutter.mysql_version != "None" %}
  database:
    <<: *networks
    image: mysql:{{cookiecutter.mysql_version}}
    ports:
      - 3306
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE={{cookiecutter.project_slug}}
    volumes:
      - ./.docker/fixtures.sql:/docker-entrypoint-initdb.d/fixtures.sql
  {% endif %}
  app:
    <<: *development-build
    <<: *networks
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=development
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=0
      {%- endif %}
    {%- if cookiecutter.mysql_version != "None" %}
    depends_on:
      - database
    {%- endif %}
    ports:
      - 8090:8090

  format-imports:
    <<: *mounted
    <<: *development-build
    command: isort {{cookiecutter.project_slug}}/. tests/.
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=development
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=1
      {%- endif %}

  format:
    <<: *mounted
    <<: *development-build
    command: black -l 79 --target-version py38 {{cookiecutter.project_slug}} tests
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=development
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=1
      {%- endif %}

  check-imports:
    <<: *development-build
    command: isort --check-only {{cookiecutter.project_slug}}/. tests/.
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=development
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=1
      {%- endif %}

  check-format:
    <<: *development-build
    command: black -l 79 --target-version py38 --check {{cookiecutter.project_slug}} tests
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=development
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=1
      {%- endif %}

  style:
    <<: *development-build
    command: pylint --reports=n --rcfile=pylintrc {{cookiecutter.project_slug}} tests
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=development
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=1
      {%- endif %}

  complexity:
    <<: *development-build
    command: xenon --max-absolute B --max-modules B --max-average A {{cookiecutter.project_slug}}
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=development
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=1
      {%- endif %}

  security-sast:
    <<: *development-build
    command: bandit -r {{cookiecutter.project_slug}}
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=development
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=1
      {%- endif %}

  test-unit:
    <<: *testing-build
    command: py.test -s tests/unit -vvvvvv --junitxml=reports/report_unit_tests.xml --cov . --cov-config .coveragerc --cov-report term-missing --cov-report xml:reports/coverage_unit.xml
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=testing
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=1
      {%- endif %}

  test-functional:
    <<: *networks
    <<: *testing-build
    command: py.test -s tests/functional -vvvvvv --junitxml=reports/report_func_tests.xml --cov . --cov-config .coveragerc --cov-report term-missing --cov-report xml:reports/coverage_functional.xml
    environment:
      - {{cookiecutter.project_slug.upper()}}_ENV=testing
      {%- if cookiecutter.mysql_version != "None" %}
      - DATABASE_IS_OPTIONAL=0
      {%- endif %}
    {%- if cookiecutter.mysql_version != "None" %}
    depends_on:
      - database
    {%- endif %}

networks:
  ns:
    driver: bridge
