version: "3.4"

x-default-build: &default-build
  build: .

x-mounted-app: &mounted-app
  volumes:
    - .:/usr/src/app

services:
  cookiecutter:
    <<: *default-build

  format-imports:
    <<: *default-build
    <<: *mounted-app
    command: isort hooks/.

  format:
    <<: *default-build
    <<: *mounted-app
    command: black -l 79 --target-version py38 hooks

  check-imports:
    <<: *default-build
    command: isort --check-only hooks/.

  check-format:
    <<: *default-build
    command: black -l 79 --target-version py38 --check hooks

  style:
    <<: *default-build
    command: pylint --reports=n --rcfile=pylintrc hooks
